# Generated by Django 3.1.2 on 2021-02-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='profile',
        ),
        migrations.AddField(
            model_name='event',
            name='Organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='Location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
