# Generated by Django 3.1.2 on 2021-02-03 23:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_auto_20210204_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 3, 23, 4, 39, 26664, tzinfo=utc)),
        ),
    ]
