# Generated by Django 3.1.2 on 2021-02-04 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_event_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 6, 33, 49, 857881, tzinfo=utc)),
        ),
    ]
