# Generated by Django 3.1.2 on 2021-02-04 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_auto_20210204_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 6, 35, 29, 521366, tzinfo=utc)),
        ),
    ]
